name: Release experimental @opensesame/core-build-library

on:
  push:
    paths:
      - '*'
    branches-ignore:
      - main

jobs:
  BumpVersionAndCreateTag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.34.0
        id: github-tag-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          TAG_CONTEXT: repo
          PRERELEASE_SUFFIX: beta
          RELEASE_BRANCHES: main
          INITIAL_VERSION: 1.0.5
          VERBOSE: false
          DRY_RUN: false
    outputs:
      new_tag: ${{ steps.github-tag-action.outputs.new_tag }}

  BuildAndPublish:
    runs-on: ubuntu-latest
    needs: BumpVersionAndCreateTag
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'

      - name: Build And Publish
        uses: opensesame/core-github-actions/build-publish@v1
        with:
          is_release: 'false'
          node_auth_token: ${{ secrets.GITHUB_TOKEN }}
          package_version: ${{ needs.BumpVersionAndCreateTag.outputs.new_tag }}
